/* Worker research-annex catalog for get_report — LIVE-SITE variant of ../src/reports.ts.
   The fail-closed id catalog (ids/titles/kinds/source_urls) is baked at BUILD time from the
   local site/ tree (catalog.gen.ts, generated by scripts/build.mjs with the same regexes as
   the Node reports.ts); document CONTENT is fetched at runtime from the live deployment
   (https://margins.ashitaorbis.com/), since the Worker has no filesystem. get_report
   reads ONLY ids in this catalog (fail-closed — no path traversal, no fuzzy matching: a
   wrong-doc fetch is a misattribution vector). Documents are served verbatim, never
   summarized. htmlToText / decodeEntities / titleOf / ARCHIVE_NOTE are byte-identical copies
   of ../src/reports.ts (parity-checked by scripts/build.mjs — the build fails on drift). */
import { SITE } from "./engine.js";
import { CATALOG, type CatalogItem } from "./catalog.gen.js";

export interface ReportEntry {
  id: string;
  title: string;
  kind: "annex-doc" | "report-section" | "front-page";
  source_url: string;
}

interface CatalogEntry extends ReportEntry {
  read(): Promise<string>; // raw HTML of the document / section, fetched from the live site
}

function decodeEntities(s: string): string {
  return s
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(Number(d)))
    .replace(/&#x([0-9a-fA-F]+);/g, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&nbsp;/g, " ");
}

export function htmlToText(html: string): string {
  let s = html
    .replace(/<script[\s\S]*?<\/script>/gi, "")
    .replace(/<style[\s\S]*?<\/style>/gi, "")
    .replace(/<!--[\s\S]*?-->/g, "");
  s = s.replace(/<(td|th)[^>]*>/gi, " | ");
  s = s.replace(/<\/?(h[1-6]|p|div|section|article|li|ul|ol|table|tr|thead|tbody|blockquote|header|footer|details|summary|figure|figcaption|pre)[^>]*>/gi, "\n");
  s = s.replace(/<br\s*\/?>/gi, "\n");
  s = s.replace(/<[^>]+>/g, "");
  s = decodeEntities(s);
  s = s.replace(/[ \t]+/g, " ").replace(/ ?\n ?/g, "\n").replace(/\n{3,}/g, "\n\n");
  return s.trim();
}

/* ---------- live-site fetch (in-isolate memo + edge cache; bodies never logged) ---------- */
const memo = new Map<string, string>();
const MEMO_CAP = 64;

async function fetchLive(path: string): Promise<string> {
  const url = SITE.calculator + path;
  const hit = memo.get(url);
  if (hit !== undefined) return hit;
  const res = await fetch(url, { cf: { cacheTtl: 300, cacheEverything: true } } as RequestInit);
  if (!res.ok) {
    throw new Error(`Live-site fetch failed (HTTP ${res.status}) for ${url} — the archived document could not be retrieved; nothing is substituted (fail closed).`);
  }
  const text = await res.text();
  if (memo.size >= MEMO_CAP) memo.clear();
  memo.set(url, text);
  return text;
}

/* Same section-slicing logic as the Node reports.ts buildCatalog (h3 id="sN" → next h3 or
   </section>), applied to the LIVE front page at call time. */
function extractSection(index: string, n: string): string {
  const heads = [...index.matchAll(/<h3 id="s(\d+)">([\s\S]*?)<\/h3>/g)];
  const i = heads.findIndex((h) => h[1] === n);
  if (i === -1) {
    throw new Error(`Section s${n} was not found on the live front page — the live site may have changed since this Worker was deployed; nothing is substituted (fail closed).`);
  }
  const start = heads[i].index!;
  const next = i + 1 < heads.length ? heads[i + 1].index! : index.indexOf("</section>", start);
  const end = next === -1 ? index.length : next;
  return index.slice(start, end);
}

function makeEntry(item: CatalogItem): CatalogEntry {
  return {
    id: item.id,
    title: item.title,
    kind: item.kind,
    source_url: item.source_url,
    read: async () => {
      const raw = await fetchLive(item.path);
      return item.section === null ? raw : extractSection(raw, item.section);
    },
  };
}

let catalog: Map<string, CatalogEntry> | null = null;

export function reportCatalog(): Map<string, CatalogEntry> {
  if (!catalog) {
    catalog = new Map(CATALOG.map((item) => [item.id, makeEntry(item)]));
  }
  return catalog;
}

export function listReports(): ReportEntry[] {
  return [...reportCatalog().values()].map(({ id, title, kind, source_url }) => ({ id, title, kind, source_url }));
}

export function validReportIds(): string[] {
  return [...reportCatalog().keys()];
}

export const ARCHIVE_NOTE =
  "Archived verbatim from the research annex — served as-is, never summarized. Any margin figures embedded in this document are quoted prose from the archived source, outside this server's honest-labeling envelope: they record what sources said, they are not derived estimates of this server.";
