// SHARE CARD — static half (bq-3550, 2026-09-27). The link preview (og:/twitter: tags + a 1200×630 PNG)
// is generated by scripts/build-share-card.mjs from figures READ OFF THE RENDERED PAGE and recorded in
// design/share-card/values.json. This suite proves the served bytes are that generation's output and
// nothing else: the tag block in site/index.html regenerates EXACTLY from values.json, the PNG is the one
// values.json hashed, it is 1200×630, and its cache-busting ?v= is the PNG's own hash. The browser half,
// tests/share-card-cdp.test.mjs, re-reads the live render against values.json, so a default that moves
// without the card being rebuilt turns the gate red.
// Run: node tests/share-card.test.mjs
import { readFileSync, existsSync, statSync } from "node:fs";
import { createHash } from "node:crypto";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { renderTagBlock, TAG_BEGIN, TAG_END, SITE_ORIGIN } from "../scripts/build-share-card.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
let failures = 0;
const assert = (name, cond, detail = "") => {
  console.log(`${cond ? "PASS" : "FAIL"}  ${name}${cond ? "" : "  — " + detail}`);
  if (!cond) failures++;
};

const index = readFileSync(join(ROOT, "site", "index.html"), "utf8");
const rec = JSON.parse(readFileSync(join(ROOT, "design", "share-card", "values.json"), "utf8"));
const pngPath = join(ROOT, "site", "share-card.png");

// 1. exactly one generated block, inside <head>
const a = index.indexOf(TAG_BEGIN), b = index.indexOf(TAG_END), head = index.indexOf("</head>");
assert("exactly one share-card block, inside <head>",
  a > 0 && b > a && index.indexOf(TAG_BEGIN, a + 1) === -1 && b < head, `begin ${a} end ${b} </head> ${head}`);
const block = index.slice(a, b + TAG_END.length);

// 2. the block is the generator's output for the recorded values — byte for byte
assert("the tag block regenerates exactly from design/share-card/values.json",
  block === renderTagBlock(rec.values, rec.png_sha256), "the block was edited by hand, or values.json moved without a rebuild");

// 2b. the card was built from the template that is committed (the pixel comparison is the browser half's)
const tplSha = createHash("sha256").update(readFileSync(join(ROOT, "design", "share-card", "card.html"))).digest("hex");
assert("values.json records the current template's hash", rec.template_sha256 === tplSha, `${rec.template_sha256} vs ${tplSha}`);

// 3. the image
assert("site/share-card.png exists", existsSync(pngPath));
const png = readFileSync(pngPath);
const sha = createHash("sha256").update(png).digest("hex");
assert("PNG signature", png.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])));
assert("IHDR is 1200×630 (the summary_large_image aspect, 1.91:1)", png.readUInt32BE(16) === 1200 && png.readUInt32BE(20) === 630,
  `${png.readUInt32BE(16)}×${png.readUInt32BE(20)}`);
assert("under 1 MB (X's limit is 5 MB; a card this size loads on a phone connection)", statSync(pngPath).size < 1024 * 1024, String(statSync(pngPath).size));
assert("values.json hashes the PNG that is served", rec.png_sha256 === sha, `${rec.png_sha256} vs ${sha}`);

// 4. the tags a crawler reads
const tag = (attrName, name) => {
  const m = block.match(new RegExp(`<meta ${attrName}="${name.replace(/[.:]/g, "\\$&")}" content="([^"]*)">`));
  return m ? m[1].replace(/&quot;/g, '"').replace(/&lt;/g, "<").replace(/&amp;/g, "&") : null;
};
const ogImage = tag("property", "og:image");
assert("og:image is absolute, same-origin, and cache-busted by the PNG's own hash",
  ogImage === `${SITE_ORIGIN}/share-card.png?v=${sha.slice(0, 12)}`, String(ogImage));
assert("twitter:card is summary_large_image", tag("name", "twitter:card") === "summary_large_image");
assert("twitter:image equals og:image", tag("name", "twitter:image") === ogImage);
assert("og:image dimensions declared 1200×630", tag("property", "og:image:width") === "1200" && tag("property", "og:image:height") === "630");
assert("og:url is the canonical URL", tag("property", "og:url") === `${SITE_ORIGIN}/` && index.includes(`<link rel="canonical" href="${SITE_ORIGIN}/">`));
const title = tag("property", "og:title"), desc = tag("property", "og:description"), alt = tag("property", "og:image:alt");
assert("og:title ≤ 70 characters", !!title && [...title].length <= 70, String(title && [...title].length));
assert("og:description ≤ 200 characters", !!desc && [...desc].length <= 200, String(desc && [...desc].length));
assert("og:image:alt ≤ 420 characters (X's alt limit)", !!alt && [...alt].length <= 420, String(alt && [...alt].length));
for (const [name, text] of [["og:description", desc], ["og:image:alt", alt]]) {
  assert(`${name} carries "not a company gross margin"`, /not a company gross margin/i.test(text || ""));
  assert(`${name} carries the scenario's billing and cost-basis assumptions`,
    [rec.values.billing, rec.values.basis].every((x) => (text || "").toLowerCase().includes(x.replace(/^(Billing|Cost basis): /, "").toLowerCase())),
    JSON.stringify([rec.values.billing, rec.values.basis]));
}

// 5. every figure in the tags is one the page renders (values.json) — no number of the card's own
const figures = new Set([rec.values.headline, rec.values.floor, ...rec.values.estimates.flatMap((e) => [e.median, e.range])]);
const figureTokens = [...figures].flatMap((f) => f.match(/\d+(?:\.\d+)?/g) || []);
for (const [name, text] of [["og:title", title], ["og:description", desc], ["og:image:alt", alt]]) {
  // Names are not figures: strip the rendered scenario and estimator names (GPT-5.6, Opus 4.x, Fable 5) first.
  let bare = text || "";
  for (const name of [rec.values.scenario, ...rec.values.scenario.split(" · "), ...rec.values.estimates.map((e) => e.who)])
    bare = bare.split(name).join(" ");
  const nums = bare.match(/\d+(?:\.\d+)?/g) || [];
  const foreign = nums.filter((n) => !figureTokens.includes(n));
  assert(`${name}: every figure is one the page renders`, foreign.length === 0, JSON.stringify(foreign));
}

// 6. the static estimate faces in index.html still say what the card says
const faces = [...index.matchAll(/<p class="est-median">([^<]*)<\/p>\s*<p class="est-range">([^<]*)<\/p>/g)].map((m) => [m[1], m[2]]);
assert("the two estimate faces in index.html match the card's recorded estimates",
  faces.length === 2 && faces.every(([med, rng], i) => med === rec.values.estimates[i].median && rng.replace(/\s+/g, " ") === rec.values.estimates[i].range),
  JSON.stringify({ faces, recorded: rec.values.estimates.map((e) => [e.median, e.range]) }));

console.log(failures ? `\n${failures} FAILURE(S)` : "\nALL SHARE-CARD CHECKS PASS");
process.exit(failures ? 1 : 0);
